"""
  Spider to scrape the list of laptops on the Best Buy Canada website to help us compare them
  and make a good decision about which one to buy.
  It takes the laptops at https://www.bestbuy.ca/en-ca/category/laptops/36711
  for how many pages we want (even all, if we choose), i.e.,
  it takes the info dynamically generated by intercepting Ajax calls.
"""
import pandas as pd
import requests
import time

class BestBuyScraper:
  """ Takes list of laptops at bestbuy.ca.
  """
  API_url = 'https://www.bestbuy.ca/api/v2/json/search?categoryid=36711&currentRegion=QC&include=facets%2C%20redirects&lang=en-CA&page={}&pageSize=24&path=&query=&exp=&sortBy=relevance&sortDir=desc'

  def get_laptops_url(self):
    items = []

    page = 1
    while True:
      response = requests.get(self.API_url.format(page))

      data = response.json()
      records = data.get('products')
      for record in records:
        item = {'Name': record['name'],
                'Price': record['regularPrice'],
                'Rating': record['customerRating'],
                '#Reviews': record['customerRatingCount'], 
                'url': record['productUrl']
               }
        items.append(item)

      print('Number of products: ', len(items))
      page += 1
      if page >= 2: # if page >= data['totalPages']: # totalPages is about 347 (8326 laptops!)
        break
  
    now = time.strftime("%Y-%m-%d-%Hh%M")

    df = pd.DataFrame(items, columns=['Name', 'Price', 'Rating', '#Reviews', 'url'])
    df.to_csv('laptops_bestbuy_'+ now + '.csv', sep=',')

scraper = BestBuyScraper()
scraper.get_laptops_url()
